version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5000:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=worldmap-dev
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 9090:8080
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: price